CREATE TABLE template (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Template ID',
  project_id BIGINT NOT NULL COMMENT 'Project ID',
  template_name VARCHAR(128) NOT NULL COMMENT 'Template name',
  template_category VARCHAR(32) NOT NULL COMMENT 'Template category: REVIEW or REPORT',
  template_type VARCHAR(64) NOT NULL COMMENT 'Template type',
  scenario VARCHAR(128) NULL COMMENT 'Applicable scenario',
  version_no VARCHAR(32) NOT NULL DEFAULT 'v1' COMMENT 'Template version number',
  file_id BIGINT NOT NULL COMMENT 'Template file ID from file_object',
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT 'Template status: ENABLED or DISABLED',
  description VARCHAR(500) NULL COMMENT 'Template description',
  metadata JSON NULL COMMENT 'Extra metadata',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
  created_by BIGINT NULL COMMENT 'Created by user ID',
  updated_by BIGINT NULL COMMENT 'Updated by user ID',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  KEY idx_template_project (project_id),
  KEY idx_template_category (template_category),
  KEY idx_template_type (template_type),
  KEY idx_template_status (status),
  KEY idx_template_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Template metadata table';

CREATE TABLE report_config (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Report config ID',
  project_id BIGINT NOT NULL COMMENT 'Project ID',
  config_name VARCHAR(128) NOT NULL COMMENT 'Config name',
  report_type VARCHAR(64) NOT NULL COMMENT 'Report type',
  template_id BIGINT NULL COMMENT 'Selected template ID; phase 1 records only and CryptoAgentV3 uses its default template',
  reference_file_ids JSON NULL COMMENT 'Reference file ID list',
  knowledge_base_ids JSON NULL COMMENT 'Knowledge base ID list',
  data_source_ids JSON NULL COMMENT 'Data source ID list',
  generation_params JSON NULL COMMENT 'Generation parameters',
  status VARCHAR(32) NOT NULL DEFAULT 'SUBMITTED' COMMENT 'Config status: DRAFT or SUBMITTED',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
  created_by BIGINT NULL COMMENT 'Created by user ID',
  updated_by BIGINT NULL COMMENT 'Updated by user ID',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  KEY idx_report_config_project (project_id),
  KEY idx_report_config_template (template_id),
  KEY idx_report_config_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Report generation config table';

CREATE TABLE report (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Report ID',
  project_id BIGINT NOT NULL COMMENT 'Project ID',
  config_id BIGINT NULL COMMENT 'Report config ID',
  task_id BIGINT NULL COMMENT 'Generate task ID',
  report_name VARCHAR(128) NOT NULL COMMENT 'Report name',
  report_type VARCHAR(64) NOT NULL COMMENT 'Report type',
  template_id BIGINT NULL COMMENT 'Selected template ID',
  engine_type VARCHAR(64) NOT NULL DEFAULT 'CRYPTO_AGENT_V3' COMMENT 'Report generation engine type',
  current_version_id BIGINT NULL COMMENT 'Current report version ID',
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT 'Report status: PENDING, PROCESSING, SUCCESS, FAILED, ARCHIVED',
  progress INT NOT NULL DEFAULT 0 COMMENT 'Report progress percentage',
  preview_url VARCHAR(500) NULL COMMENT 'Preview URL',
  error_message TEXT NULL COMMENT 'Failure reason',
  started_at DATETIME NULL COMMENT 'Start time',
  finished_at DATETIME NULL COMMENT 'Finish time',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
  created_by BIGINT NULL COMMENT 'Created by user ID',
  updated_by BIGINT NULL COMMENT 'Updated by user ID',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  KEY idx_report_project (project_id),
  KEY idx_report_task (task_id),
  KEY idx_report_type (report_type),
  KEY idx_report_status (status),
  KEY idx_report_template (template_id),
  KEY idx_report_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Report table';

CREATE TABLE report_version (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Report version ID',
  project_id BIGINT NOT NULL COMMENT 'Project ID',
  report_id BIGINT NOT NULL COMMENT 'Report ID',
  version_no INT NOT NULL COMMENT 'Version number',
  word_file_id BIGINT NULL COMMENT 'Generated Word file ID',
  pdf_file_id BIGINT NULL COMMENT 'Generated PDF file ID',
  source_snapshot JSON NULL COMMENT 'Generation source snapshot',
  engine_response JSON NULL COMMENT 'Report engine response summary',
  content_hash VARCHAR(128) NULL COMMENT 'Content hash',
  status VARCHAR(32) NOT NULL DEFAULT 'SUCCESS' COMMENT 'Version status: SUCCESS or FAILED',
  error_message TEXT NULL COMMENT 'Failure reason',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
  created_by BIGINT NULL COMMENT 'Created by user ID',
  updated_by BIGINT NULL COMMENT 'Updated by user ID',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  UNIQUE KEY uk_report_version (report_id, version_no, deleted),
  KEY idx_report_version_project (project_id),
  KEY idx_report_version_report (report_id),
  KEY idx_report_version_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Report version table';
