CREATE TABLE file_parse_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'Primary key ID',
  project_id BIGINT NOT NULL COMMENT 'Project ID',
  file_id BIGINT NOT NULL COMMENT 'Source file ID',
  source_file_hash VARCHAR(128) NULL COMMENT 'Source file hash at parse time',
  source_content_type VARCHAR(128) NULL COMMENT 'Source content type',
  parse_type VARCHAR(64) NOT NULL COMMENT 'Parse type',
  result_format VARCHAR(32) NOT NULL COMMENT 'MARKDOWN or TEXT',
  parser_provider VARCHAR(64) NOT NULL COMMENT 'Parser provider',
  parser_model VARCHAR(128) NULL COMMENT 'Parser model name',
  status VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT 'Parse status',
  progress INT NOT NULL DEFAULT 0 COMMENT 'Parse progress 0-100',
  current_stage VARCHAR(64) NULL COMMENT 'Current parse stage',
  result_object_name VARCHAR(500) NULL COMMENT 'Parsed result object name',
  result_file_id BIGINT NULL COMMENT 'Optional registered result file ID',
  content_preview TEXT NULL COMMENT 'Short parsed content preview',
  error_message TEXT NULL COMMENT 'Error message',
  metadata JSON NULL COMMENT 'Provider usage, page count, confidence, and diagnostics',
  started_at DATETIME NULL COMMENT 'Start time',
  finished_at DATETIME NULL COMMENT 'Finish time',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Created time',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Updated time',
  created_by BIGINT NULL COMMENT 'Created by user ID',
  updated_by BIGINT NULL COMMENT 'Updated by user ID',
  deleted TINYINT NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
  KEY idx_file_parse_project (project_id),
  KEY idx_file_parse_file (file_id),
  KEY idx_file_parse_status (status),
  KEY idx_file_parse_hash (file_id, source_file_hash),
  KEY idx_file_parse_created_at (created_at),
  KEY idx_file_parse_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='File parse record table';
