UPDATE report SET status = 'GENERATING' WHERE status IN ('PENDING', 'PROCESSING') AND deleted = 0;
UPDATE report SET status = 'COMPLETED' WHERE status = 'SUCCESS' AND deleted = 0;

ALTER TABLE report
  MODIFY COLUMN status VARCHAR(32) NOT NULL DEFAULT 'GENERATING' COMMENT 'Report status: DRAFT, GENERATING, COMPLETED, FAILED, ARCHIVED, DELETED';
